server:
  port: 8600

spring:
  application:
    name: course-service
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
<<<<<<< HEAD
          issuer-uri: http://localhost:8081/realms/ecole
=======
          issuer-uri: http://localhost:8081/realms/school
  kafka:
    bootstrap-servers: localhost:9092
>>>>>>> 3d3f149edd9ced9a77b73e5f5e497569be4a866f

  datasource:
    url: jdbc:postgresql://localhost:5433/course_db
    username: mourad
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
